# Generated by Django 4.0.4 on 2022-11-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_machine_translation_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_finder',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[['ARTS', 'ARTS'], ['ARTS & CULTURE', 'ARTS & CULTURE'], ['BLACK VOICES', 'BLACK VOICES'], ['BUSINESS', 'BUSINESS'], ['COLLEGE', 'COLLEGE'], ['COMEDY', 'COMEDY'], ['CRIME', 'CRIME'], ['CULTURE & ARTS', 'CULTURE & ARTS'], ['DIVORCE', 'DIVORCE'], ['EDUCATION', 'EDUCATION'], ['ENTERTAINMENT', 'ENTERTAINMENT'], ['ENVIRONMENT', 'ENVIRONMENT'], ['FIFTY', 'FIFTY'], ['FOOD & DRINK', 'FOOD & DRINK'], ['GOOD NEWS', 'GOOD NEWS'], ['GREEN', 'GREEN'], ['HEALTHY LIVING', 'HEALTHY LIVING'], ['HOME & LIVING', 'HOME & LIVING'], ['IMPACT', 'IMPACT'], [
                 'LATINO VOICES', 'LATINO VOICES'], ['MEDIA', 'MEDIA'], ['MONEY', 'MONEY'], ['PARENTING', 'PARENTING'], ['PARENTS', 'PARENTS'], ['POLITICS', 'POLITICS'], ['QUEER VOICES', 'QUEER VOICES'], ['RELIGION', 'RELIGION'], ['SCIENCE', 'SCIENCE'], ['SPORTS', 'SPORTS'], ['STYLE', 'STYLE'], ['STYLE & BEAUTY', 'STYLE & BEAUTY'], ['TASTE', 'TASTE'], ['TECH', 'TECH'], ['THE WORLDPOST', 'THE WORLDPOST'], ['TRAVEL', 'TRAVEL'], ['WEDDINGS', 'WEDDINGS'], ['WEIRD NEWS', 'WEIRD NEWS'], ['WELLNESS', 'WELLNESS'], ['WOMEN', 'WOMEN'], ['WORLD NEWS', 'WORLD NEWS'], ['WORLDPOST', 'WORLDPOST'], ['all', 'all']], max_length=15)),
            ],
        ),
    ]
