# Generated by Django 4.0.4 on 2022-11-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_article_finder'),
    ]

    operations = [
        migrations.CreateModel(
            name='signin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password1', models.CharField(max_length=250)),
                ('password2', models.CharField(max_length=250)),
            ],
        ),
    ]
