# Generated by Django 4.0.4 on 2022-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_signin_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_transport_request_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=250)),
                ('to', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('date_time', models.DateTimeField()),
                ('flexible_timimg', models.BooleanField()),
                ('no_of_assets', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('asset_type', models.CharField(max_length=250)),
                ('asset_sensitivity', models.CharField(max_length=250)),
                ('whom_to_deliver', models.CharField(max_length=250)),
            ],
        ),
    ]
