# Generated by Django 4.0.4 on 2022-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_asset_transport_request_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='share_travel_information_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=250)),
                ('to', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('date_time', models.DateTimeField()),
                ('flexible_timimg', models.BooleanField()),
                ('medium', models.CharField(max_length=250)),
                ('no_of_assets', models.CharField(max_length=250)),
            ],
        ),
    ]
